main: dev.minecraftdorado.blackmarket.mainclass.MainClass
name: BlackMarket
author: MinecraftDorado
version: 1.34.1
api-version: 1.13
softdepend: [Vault, PlayerPoints, Multiverse-Core]
commands:
  bm:
    description: Use BlackMarket commands.
    alias: [blackmarket]

permissions:
  blackmarket.admin:
    description: Allows the use of all commands
    default: op
    children:
      blackmarket.limit.*: true
      blackmarket.reload: true
      blackmarket.npc.*: true
      blackmarket.open: true
      blackmarket.remove_item: true
  blackmarket.npc.*:
    description: Allows the use of commands for NPCs
    default: op
    children:
      blackmarket.npc.set: true
      blackmarket.npc.remove: true
  blackmarket.npc.set:
    description: Allows usage of the /bm setnpc command
  blackmarket.npc.remove:
    description: Allows usage of the /bm removenpc command
  blackmarket.limit:
    description: Limit of published articles
  blackmarket.reload:
    description: Allows usage of the /bm reload command
  blackmarket.open:
    description: Allows usage of the /bm open command
  blackmarket.remove_item:
    description: Allow cancel any post